# Generated by Django 2.0.9 on 2019-03-04 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPull',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(blank=True, null=True, verbose_name='Created')),
                ('time_updated', models.DateTimeField(blank=True, null=True, verbose_name='Updated')),
                ('compare_data', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(blank=True, null=True, verbose_name='Created')),
                ('time_updated', models.DateTimeField(blank=True, null=True, verbose_name='Updated')),
                ('env_name', models.CharField(help_text='Identifier of the source env e.g. develop', max_length=20, unique=True)),
                ('env_url', models.URLField(help_text='Environment base URL where the data will be pulled from. Scheme included and do not include endslash', verbose_name='environment base URL')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='datapull',
            name='data_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_pulls', to='data_sync.DataSource'),
        ),
    ]
