# Generated by Django 2.2 on 2019-05-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sync', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='env_url',
            field=models.URLField(help_text="Environment base URL where the data will be pulled from. Scheme included and do not include endslash.This value is very dependant on the urls.py setup, refers to django_data_sync docs for further explanation.Usually it's https://example.com/api", verbose_name='environment base URL'),
        ),
    ]
