# Generated by Django 2.2 on 2019-06-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sync', '0004_auto_20190602_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapull',
            name='status',
            field=models.CharField(blank=True, choices=[('', ''), ('SUCCEED', 'SUCCEED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('FAILED', 'FAILED')], default='', help_text='status can become stuck/stale at IN_PROGRESS, if you wait long enough but the status does not change from IN_PROGRESS, please do another sync', max_length=20),
        ),
    ]
